listeners:
  - protocol_type: mysql
    socket_address:
      address: 0.0.0.0
      port: 13306
    config:
      users:
        dksl: "123456"
      server_version: "8.0.27"
    executor: redirect

executors:
  - name: redirect
    mode: shd
    config:
      db_groups:
        - name: drug_0
          load_balance_algorithm: RandomWeight
          data_sources:
            - name: drug_0
              weight: r10w10
        - name: drug_1
          load_balance_algorithm: RandomWeight
          data_sources:
            - name: drug_1
              weight: r10w10
      logic_tables:
        - db_name: drug
          table_name: drug_resource
          allow_full_scan: true
          sharding_rule:
            column: id
            sharding_algorithm: NumberMod
          topology:
            "0": 0-4
            "1": 5-9

data_source_cluster:
  - name: drug_0
    capacity: 10
    max_capacity: 20
    idle_timeout: 60s
    dsn: root:123456@tcp(dbpack-mysql1:3306)/drug?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8mb4,utf8
    ping_interval: 20s
    ping_times_for_change_status: 3

  - name: drug_1
    capacity: 10
    max_capacity: 20
    idle_timeout: 60s
    dsn: root:123456@tcp(dbpack-mysql2:3306)/drug?timeout=60s&readTimeout=60s&writeTimeout=60s&parseTime=true&loc=Local&charset=utf8mb4,utf8
    ping_interval: 20s
    ping_times_for_change_status: 3

http_listen_port: 9999